# Generated by Django 5.2.6 on 2026-06-13 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ESP32', 'ESP32'), ('GPS_NEO6M', 'GPS NEO-6M')], default='ESP32', max_length=20)),
                ('identificador', models.CharField(help_text='MAC o ID único', max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
                'db_table': 'dispositivo_iot',
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'db_table': 'parada',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(help_text='Ruta Angular, ej: /dashboard', max_length=100)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría del Sistema',
                'verbose_name_plural': 'Auditorías del Sistema',
                'db_table': 'auditoria_sistema',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('licencia', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductor',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.conductor')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.vehiculo')),
            ],
            options={
                'verbose_name': 'Asignación de Ruta',
                'verbose_name_plural': 'Asignaciones de Rutas',
                'db_table': 'asignacion_ruta',
            },
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('activar', 'Activar'), ('desactivar', 'Desactivar')], max_length=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('ejecutado', 'Ejecutado'), ('fallido', 'Fallido')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='api.dispositivoiot')),
            ],
            options={
                'verbose_name': 'Comando Remoto',
                'verbose_name_plural': 'Comandos Remotos',
                'db_table': 'comando_remoto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRecorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='api.asignacionruta')),
            ],
            options={
                'verbose_name': 'Historial de Recorrido',
                'verbose_name_plural': 'Historial de Recorridos',
                'db_table': 'historial_recorrido',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exitoso', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('comando', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='api.comandoremoto')),
            ],
            options={
                'verbose_name': 'Respuesta de Comando',
                'verbose_name_plural': 'Respuestas de Comandos',
                'db_table': 'respuesta_comando',
            },
        ),
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=15)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.ruta')),
            ],
            options={
                'verbose_name': 'Horario de Ruta',
                'verbose_name_plural': 'Horarios de Rutas',
                'db_table': 'horario_ruta',
            },
        ),
        migrations.CreateModel(
            name='UbicacionGps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('velocidad', models.FloatField(default=0.0, help_text='km/h')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='api.dispositivoiot')),
            ],
            options={
                'verbose_name': 'Ubicación GPS',
                'verbose_name_plural': 'Ubicaciones GPS',
                'db_table': 'ubicacion_gps',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='activo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.vehiculo')),
            ],
            options={
                'verbose_name': 'Estado de Operación',
                'verbose_name_plural': 'Estados de Operación',
                'db_table': 'estado_operacion',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='api.vehiculo'),
        ),
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desconexion', 'Desconexión de dispositivo'), ('velocidad', 'Velocidad excesiva'), ('fuera_ruta', 'Vehículo fuera de ruta'), ('sin_gps', 'Sin señal GPS'), ('general', 'General')], default='general', max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('advertencia', 'Advertencia'), ('critico', 'Crítico')], default='info', max_length=15)),
                ('mensaje', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='api.dispositivoiot')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='api.vehiculo')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'db_table': 'alerta_sistema',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RolRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.rol')),
            ],
            options={
                'verbose_name': 'Rol Recurso',
                'verbose_name_plural': 'Roles Recursos',
                'db_table': 'rol_recurso',
                'unique_together': {('rol', 'recurso')},
            },
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_paradas', to='api.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_paradas', to='api.ruta')),
            ],
            options={
                'verbose_name': 'Ruta Parada',
                'verbose_name_plural': 'Rutas Paradas',
                'db_table': 'ruta_parada',
                'ordering': ['orden'],
                'unique_together': {('ruta', 'parada')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Rol',
                'verbose_name_plural': 'Usuarios Roles',
                'db_table': 'usuario_rol',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
